import React from 'react'
import "../styles/Search.css"
import {
  PodcastImg,
  AudiobooksImg,
  LiveEventsImg,
  MadeForYouImg,
  NewReleasesImg,
  PopImg,
  MoodImg,
  HipHopImg,
  PartyImg,
  ChartsImg,
  DanceElectricImg,
  WorkoutImg,
  EqualImg,
  AlternativeImg,
  DiscoverImg,
  FrequencyImg,
  IndieImg,
  NetflixImg,
  GlowImg,
  RockImg,
  RnBImg,
  ThrowbackImg,
  DisneyImg,
  RadarImg,
  WellnessImg,
  CountryImg,
  KPopImg,
  ChillImg,
  SleepImg,
  AtHomeImg,
  DecadesImg,
  LoveImg,
  StudentImg,
  DesiImg,
  JazzImg,
  TrendingImg,
  InTheCarImg,
  ClassicalImg,
  AnimeImg,
  FolkAcousticImg,
  FocusImg,
  SoulImg,
  KidsFamilyImg,
  GamingImg,
  CaribbeanImg,
  AfroImg,
  MetalImg,
  TVMoviesImg,
  InstrumentalImg,
  PunkImg,
  AmbientImg,
  BluesImg,
  CookingDiningImg,
  TravelImg,
  SongWritersImg,
  NatureNoiseImg,
  FunkDiscoImg,
  LatinImg,
  LeagueOfLegendsImg,
  SpotifySinglesImg,
  SummerImg,
  ArabImg,
  BlackHistoryIsNowImg,
  ChristianGospelImg,
  FreshFindsImg,
  HappyHolidaysImg,
  MusicTalkImg,
  TasteMakersImg,
  RamadanImg,
} from "../assets/searchcards_assets/CardImages";
import SearchCard from '../components/SearchCard'
import { SearchRounded } from '@mui/icons-material';

function Search({spotify, refObj}) {

    const data = [
      { img: PodcastImg, title: "Podcast", bgColour: "#E23300" },
      { img: AudiobooksImg, title: "Audiobooks", bgColour: "#283EA3" },
      { img: LiveEventsImg, title: "Live Events", bgColour: "#7458FF" },
      { img: MadeForYouImg, title: "Made For You", bgColour: "#1E3264" },
      { img: NewReleasesImg, title: "New Releases", bgColour: "#E8135B" },
      { img: PopImg, title: "Pop", bgColour: "#148A09" },
      { img: MoodImg, title: "Mood", bgColour: "#E2128C" },
      { img: HipHopImg, title: "Hip-Hop", bgColour: "#BC5900" },
      { img: PartyImg, title: "Party", bgColour: "#537AA1" },
      { img: ChartsImg, title: "Charts", bgColour: "#8D67AC" },
      { img: DanceElectricImg, title: "Dance/Electric", bgColour: "#D84000" },
      { img: WorkoutImg, title: "Workout", bgColour: "#777777" },
      { img: EqualImg, title: "EQUAL", bgColour: "#056A52" },
      { img: AlternativeImg, title: "Alternative", bgColour: "#E9142A" },
      { img: DiscoverImg, title: "Discover", bgColour: "#8D67AC" },
      { img: FrequencyImg, title: "Frequency", bgColour: "#0E73EC" },
      { img: IndieImg, title: "Indie", bgColour: "#E9142A" },
      { img: NetflixImg, title: "Netflix", bgColour: "#EB1F32" },
      { img: GlowImg, title: "GLOW", bgColour: "#0E73EC" },
      { img: RockImg, title: "Rock", bgColour: "#E9142A" },
      { img: RnBImg, title: "R&B", bgColour: "#DC168C" },
      { img: ThrowbackImg, title: "Throwback", bgColour: "#8D67AC" },
      { img: DisneyImg, title: "Disney", bgColour: "#0F72EA" },
      { img: RadarImg, title: "RADAR", bgColour: "#777777" },
      { img: WellnessImg, title: "Wellness", bgColour: "#A66752" },
      { img: CountryImg, title: "Country", bgColour: "#D84000" },
      { img: KPopImg, title: "K-pop", bgColour: "#148A09" },
      { img: ChillImg, title: "Chill", bgColour: "#D84000" },
      { img: SleepImg, title: "Sleep", bgColour: "#1E3264" },
      { img: AtHomeImg, title: "At Home", bgColour: "#5179A1" },
      { img: DecadesImg, title: "Decades", bgColour: "#BA5D06" },
      { img: LoveImg, title: "Love", bgColour: "#E61F32" },
      { img: StudentImg, title: "Student", bgColour: "#BA5D06" },
      { img: DesiImg, title: "Desi", bgColour: "#E23300" },
      { img: JazzImg, title: "Jazz", bgColour: "#777777" },
      { img: TrendingImg, title: "Trending", bgColour: "#B02898" },
      { img: InTheCarImg, title: "In the car", bgColour: "#CDF565" },
      { img: ClassicalImg, title: "Classical", bgColour: "#7D4C32" },
      { img: AnimeImg, title: "Anime", bgColour: "#E41C63" },
      { img: FolkAcousticImg, title: "Folk & Acoustic", bgColour: "#BC5900" },
      { img: FocusImg, title: "Focus", bgColour: "#513750" },
      { img: SoulImg, title: "Soul", bgColour: "#DC168C" },
      { img: KidsFamilyImg, title: "Kids & Family", bgColour: "#8D67AC" },
      { img: GamingImg, title: "Gaming", bgColour: "#E8135B" },
      { img: CaribbeanImg, title: "Caribbean", bgColour: "#0E73EC" },
      { img: AfroImg, title: "Afro", bgColour: "#D84000" },
      { img: MetalImg, title: "Metal", bgColour: "#E9142A" },
      { img: TVMoviesImg, title: "TV & Movies", bgColour: "#AF2897" },
      { img: InstrumentalImg, title: "Instrumental", bgColour: "#537AA1" },
      { img: PunkImg, title: "Punk", bgColour: "#1E3264" },
      { img: AmbientImg, title: "Ambient", bgColour: "#477D96" },
      { img: BluesImg, title: "Blues", bgColour: "#B06239" },
      { img: CookingDiningImg, title: "Cooking & Dining", bgColour: "#BA5D06" },
      { img: TravelImg, title: "Travel", bgColour: "#0D72ED" },
      { img: SongWritersImg, title: "Song Writers", bgColour: "#8C1A32" },
      { img: NatureNoiseImg, title: "Nature & Noise", bgColour: "#477D96" },
      { img: FunkDiscoImg, title: "Funk & Disco", bgColour: "#E61F32" },
      { img: LatinImg, title: "Latin", bgColour: "#E2128C" },
      { img: LeagueOfLegendsImg, title: "League of Legends", bgColour: "#148A09" },
      { img: SpotifySinglesImg, title: "Spotify Singles", bgColour: "#777777" },
      { img: SummerImg, title: "Summer", bgColour: "#27856A" },
      { img: ArabImg, title: "Arab", bgColour: "#0E73EC" },
      { img: BlackHistoryIsNowImg, title: "Black History Is Now", bgColour: "#283EA3" },
      { img: ChristianGospelImg, title: "Christian & Gospel", bgColour: "#0E73EC" },
      { img: FreshFindsImg, title: "Fresh Finds", bgColour: "#FF0090" },
      { img: HappyHolidaysImg, title: "Happy Holidays", bgColour: "#8C1A32" },
      { img: MusicTalkImg, title: "Music + Talk", bgColour: "#FF4632" },
      { img: TasteMakersImg, title: "Tastemakers", bgColour: "#E8135B" },
      { img: RamadanImg, title: "Ramadan", bgColour: "#513750" },
    ];

  return (
        <div className="search--body">
        {/* <div className="searchbar--cont">
          <SearchRounded sx={{ fontSize: '25px', color: 'black' }} className="searchbar--more-btn searchbar--icon" />
          <input className='searchbar--input' type="text" placeholder="What do you want to listen to?"/>
        </div> */}
        <h2 ref={refObj} className='search--page-title'>Browse all</h2>
        <div className='search--grid'>
          {data.map((d, index) => {
            return <SearchCard key={index} img={d.img} title={d.title} bgColour={d.bgColour}/>
          })}
        </div>
      </div>
  );
}

export default Search
